var dir_210a2c16dd6ca7d426c089f432d50f87 =
[
    [ "macosx", "dir_910cbc68cb8f239ed6c91a55934ce687.html", "dir_910cbc68cb8f239ed6c91a55934ce687" ],
    [ "__init__.py", "pygame_2examples_2____init_____8py.html", null ],
    [ "aacircle.py", "aacircle_8py.html", "aacircle_8py" ],
    [ "aliens.py", "aliens_8py.html", "aliens_8py" ],
    [ "arraydemo.py", "arraydemo_8py.html", "arraydemo_8py" ],
    [ "blend_fill.py", "blend__fill_8py.html", "blend__fill_8py" ],
    [ "blit_blends.py", "blit__blends_8py.html", "blit__blends_8py" ],
    [ "camera.py", "examples_2camera_8py.html", "examples_2camera_8py" ],
    [ "chimp.py", "chimp_8py.html", "chimp_8py" ],
    [ "cursors.py", "examples_2cursors_8py.html", "examples_2cursors_8py" ],
    [ "eventlist.py", "eventlist_8py.html", "eventlist_8py" ],
    [ "fastevents.py", "fastevents_8py.html", "fastevents_8py" ],
    [ "fonty.py", "fonty_8py.html", "fonty_8py" ],
    [ "freetype_misc.py", "freetype__misc_8py.html", "freetype__misc_8py" ],
    [ "glcube.py", "glcube_8py.html", "glcube_8py" ],
    [ "headless_no_windows_needed.py", "headless__no__windows__needed_8py.html", "headless__no__windows__needed_8py" ],
    [ "intro.py", "intro_8py.html", "intro_8py" ],
    [ "liquid.py", "liquid_8py.html", "liquid_8py" ],
    [ "mask.py", "mask_8py.html", "mask_8py" ],
    [ "midi.py", "examples_2midi_8py.html", "examples_2midi_8py" ],
    [ "moveit.py", "moveit_8py.html", "moveit_8py" ],
    [ "oldalien.py", "oldalien_8py.html", "oldalien_8py" ],
    [ "overlay.py", "overlay_8py.html", "overlay_8py" ],
    [ "pixelarray.py", "pixelarray_8py.html", "pixelarray_8py" ],
    [ "playmus.py", "playmus_8py.html", "playmus_8py" ],
    [ "prevent_display_stretching.py", "prevent__display__stretching_8py.html", "prevent__display__stretching_8py" ],
    [ "scaletest.py", "scaletest_8py.html", "scaletest_8py" ],
    [ "scrap_clipboard.py", "scrap__clipboard_8py.html", "scrap__clipboard_8py" ],
    [ "scroll.py", "scroll_8py.html", "scroll_8py" ],
    [ "sound.py", "sound_8py.html", "sound_8py" ],
    [ "sound_array_demos.py", "sound__array__demos_8py.html", "sound__array__demos_8py" ],
    [ "stars.py", "stars_8py.html", "stars_8py" ],
    [ "testsprite.py", "testsprite_8py.html", "testsprite_8py" ],
    [ "vgrade.py", "vgrade_8py.html", "vgrade_8py" ]
];