var namespacegevent_1_1events =
[
    [ "_AbstractMemoryEvent", "classgevent_1_1events_1_1___abstract_memory_event.html", "classgevent_1_1events_1_1___abstract_memory_event" ],
    [ "_PatchAllMixin", "classgevent_1_1events_1_1___patch_all_mixin.html", "classgevent_1_1events_1_1___patch_all_mixin" ],
    [ "DoNotPatch", "classgevent_1_1events_1_1_do_not_patch.html", null ],
    [ "EventLoopBlocked", "classgevent_1_1events_1_1_event_loop_blocked.html", "classgevent_1_1events_1_1_event_loop_blocked" ],
    [ "GeventDidPatchAllEvent", "classgevent_1_1events_1_1_gevent_did_patch_all_event.html", null ],
    [ "GeventDidPatchBuiltinModulesEvent", "classgevent_1_1events_1_1_gevent_did_patch_builtin_modules_event.html", null ],
    [ "GeventDidPatchEvent", "classgevent_1_1events_1_1_gevent_did_patch_event.html", null ],
    [ "GeventDidPatchModuleEvent", "classgevent_1_1events_1_1_gevent_did_patch_module_event.html", "classgevent_1_1events_1_1_gevent_did_patch_module_event" ],
    [ "GeventPatchEvent", "classgevent_1_1events_1_1_gevent_patch_event.html", "classgevent_1_1events_1_1_gevent_patch_event" ],
    [ "GeventWillPatchAllEvent", "classgevent_1_1events_1_1_gevent_will_patch_all_event.html", "classgevent_1_1events_1_1_gevent_will_patch_all_event" ],
    [ "GeventWillPatchEvent", "classgevent_1_1events_1_1_gevent_will_patch_event.html", null ],
    [ "GeventWillPatchModuleEvent", "classgevent_1_1events_1_1_gevent_will_patch_module_event.html", "classgevent_1_1events_1_1_gevent_will_patch_module_event" ],
    [ "IEventLoopBlocked", "classgevent_1_1events_1_1_i_event_loop_blocked.html", null ],
    [ "IGeventDidPatchAllEvent", "classgevent_1_1events_1_1_i_gevent_did_patch_all_event.html", null ],
    [ "IGeventDidPatchBuiltinModulesEvent", "classgevent_1_1events_1_1_i_gevent_did_patch_builtin_modules_event.html", null ],
    [ "IGeventDidPatchEvent", "classgevent_1_1events_1_1_i_gevent_did_patch_event.html", null ],
    [ "IGeventDidPatchModuleEvent", "classgevent_1_1events_1_1_i_gevent_did_patch_module_event.html", null ],
    [ "IGeventPatchEvent", "classgevent_1_1events_1_1_i_gevent_patch_event.html", null ],
    [ "IGeventWillPatchAllEvent", "classgevent_1_1events_1_1_i_gevent_will_patch_all_event.html", "classgevent_1_1events_1_1_i_gevent_will_patch_all_event" ],
    [ "IGeventWillPatchEvent", "classgevent_1_1events_1_1_i_gevent_will_patch_event.html", null ],
    [ "IGeventWillPatchModuleEvent", "classgevent_1_1events_1_1_i_gevent_will_patch_module_event.html", null ],
    [ "IMemoryUsageThresholdExceeded", "classgevent_1_1events_1_1_i_memory_usage_threshold_exceeded.html", null ],
    [ "IMemoryUsageUnderThreshold", "classgevent_1_1events_1_1_i_memory_usage_under_threshold.html", null ],
    [ "IPeriodicMonitorThread", "classgevent_1_1events_1_1_i_periodic_monitor_thread.html", "classgevent_1_1events_1_1_i_periodic_monitor_thread" ],
    [ "IPeriodicMonitorThreadStartedEvent", "classgevent_1_1events_1_1_i_periodic_monitor_thread_started_event.html", null ],
    [ "MemoryUsageThresholdExceeded", "classgevent_1_1events_1_1_memory_usage_threshold_exceeded.html", null ],
    [ "MemoryUsageUnderThreshold", "classgevent_1_1events_1_1_memory_usage_under_threshold.html", "classgevent_1_1events_1_1_memory_usage_under_threshold" ],
    [ "PeriodicMonitorThreadStartedEvent", "classgevent_1_1events_1_1_periodic_monitor_thread_started_event.html", "classgevent_1_1events_1_1_periodic_monitor_thread_started_event" ]
];