var namespacepygame_1_1tests_1_1run__tests____tests_1_1exclude_1_1magic__tag__test =
[
    [ "KeyModuleTest", "classpygame_1_1tests_1_1run__tests____tests_1_1exclude_1_1magic__tag__test_1_1_key_module_test.html", "classpygame_1_1tests_1_1run__tests____tests_1_1exclude_1_1magic__tag__test_1_1_key_module_test" ]
];