var namespacepkg__resources =
[
    [ "_vendor", "namespacepkg__resources_1_1__vendor.html", "namespacepkg__resources_1_1__vendor" ],
    [ "extern", "namespacepkg__resources_1_1extern.html", "namespacepkg__resources_1_1extern" ],
    [ "_ReqExtras", "classpkg__resources_1_1___req_extras.html", "classpkg__resources_1_1___req_extras" ],
    [ "ContextualVersionConflict", "classpkg__resources_1_1_contextual_version_conflict.html", "classpkg__resources_1_1_contextual_version_conflict" ],
    [ "DefaultProvider", "classpkg__resources_1_1_default_provider.html", "classpkg__resources_1_1_default_provider" ],
    [ "DistInfoDistribution", "classpkg__resources_1_1_dist_info_distribution.html", null ],
    [ "Distribution", "classpkg__resources_1_1_distribution.html", "classpkg__resources_1_1_distribution" ],
    [ "DistributionNotFound", "classpkg__resources_1_1_distribution_not_found.html", "classpkg__resources_1_1_distribution_not_found" ],
    [ "EggInfoDistribution", "classpkg__resources_1_1_egg_info_distribution.html", null ],
    [ "EggMetadata", "classpkg__resources_1_1_egg_metadata.html", "classpkg__resources_1_1_egg_metadata" ],
    [ "EggProvider", "classpkg__resources_1_1_egg_provider.html", "classpkg__resources_1_1_egg_provider" ],
    [ "EmptyProvider", "classpkg__resources_1_1_empty_provider.html", "classpkg__resources_1_1_empty_provider" ],
    [ "EntryPoint", "classpkg__resources_1_1_entry_point.html", "classpkg__resources_1_1_entry_point" ],
    [ "Environment", "classpkg__resources_1_1_environment.html", "classpkg__resources_1_1_environment" ],
    [ "ExtractionError", "classpkg__resources_1_1_extraction_error.html", null ],
    [ "FileMetadata", "classpkg__resources_1_1_file_metadata.html", "classpkg__resources_1_1_file_metadata" ],
    [ "IMetadataProvider", "classpkg__resources_1_1_i_metadata_provider.html", "classpkg__resources_1_1_i_metadata_provider" ],
    [ "IResourceProvider", "classpkg__resources_1_1_i_resource_provider.html", "classpkg__resources_1_1_i_resource_provider" ],
    [ "MemoizedZipManifests", "classpkg__resources_1_1_memoized_zip_manifests.html", "classpkg__resources_1_1_memoized_zip_manifests" ],
    [ "NoDists", "classpkg__resources_1_1_no_dists.html", "classpkg__resources_1_1_no_dists" ],
    [ "NullProvider", "classpkg__resources_1_1_null_provider.html", "classpkg__resources_1_1_null_provider" ],
    [ "PathMetadata", "classpkg__resources_1_1_path_metadata.html", "classpkg__resources_1_1_path_metadata" ],
    [ "PEP440Warning", "classpkg__resources_1_1_p_e_p440_warning.html", null ],
    [ "Requirement", "classpkg__resources_1_1_requirement.html", "classpkg__resources_1_1_requirement" ],
    [ "RequirementParseError", "classpkg__resources_1_1_requirement_parse_error.html", "classpkg__resources_1_1_requirement_parse_error" ],
    [ "ResolutionError", "classpkg__resources_1_1_resolution_error.html", "classpkg__resources_1_1_resolution_error" ],
    [ "ResourceManager", "classpkg__resources_1_1_resource_manager.html", "classpkg__resources_1_1_resource_manager" ],
    [ "UnknownExtra", "classpkg__resources_1_1_unknown_extra.html", null ],
    [ "VersionConflict", "classpkg__resources_1_1_version_conflict.html", "classpkg__resources_1_1_version_conflict" ],
    [ "WorkingSet", "classpkg__resources_1_1_working_set.html", "classpkg__resources_1_1_working_set" ],
    [ "ZipManifests", "classpkg__resources_1_1_zip_manifests.html", "classpkg__resources_1_1_zip_manifests" ],
    [ "ZipProvider", "classpkg__resources_1_1_zip_provider.html", "classpkg__resources_1_1_zip_provider" ]
];