var namespacemore__itertools_1_1tests_1_1test__recipes =
[
    [ "AccumulateTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_accumulate_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_accumulate_tests" ],
    [ "AllEqualTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_all_equal_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_all_equal_tests" ],
    [ "ConsumeTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_consume_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_consume_tests" ],
    [ "DotproductTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_dotproduct_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_dotproduct_tests" ],
    [ "FirstTrueTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_first_true_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_first_true_tests" ],
    [ "FlattenTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_flatten_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_flatten_tests" ],
    [ "GrouperTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_grouper_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_grouper_tests" ],
    [ "IterExceptTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_iter_except_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_iter_except_tests" ],
    [ "NcyclesTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_ncycles_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_ncycles_tests" ],
    [ "NthCombinationTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_nth_combination_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_nth_combination_tests" ],
    [ "NthTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_nth_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_nth_tests" ],
    [ "PadnoneTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_padnone_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_padnone_tests" ],
    [ "PairwiseTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_pairwise_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_pairwise_tests" ],
    [ "PartitionTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_partition_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_partition_tests" ],
    [ "PowersetTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_powerset_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_powerset_tests" ],
    [ "PrependTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_prepend_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_prepend_tests" ],
    [ "QuantifyTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_quantify_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_quantify_tests" ],
    [ "RandomCombinationTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_random_combination_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_random_combination_tests" ],
    [ "RandomCombinationWithReplacementTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_random_combination_with_replacement_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_random_combination_with_replacement_tests" ],
    [ "RandomPermutationTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_random_permutation_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_random_permutation_tests" ],
    [ "RandomProductTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_random_product_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_random_product_tests" ],
    [ "RepeatfuncTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_repeatfunc_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_repeatfunc_tests" ],
    [ "RoundrobinTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_roundrobin_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_roundrobin_tests" ],
    [ "TabulateTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_tabulate_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_tabulate_tests" ],
    [ "TailTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_tail_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_tail_tests" ],
    [ "TakeTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_take_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_take_tests" ],
    [ "UniqueEverseenTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_unique_everseen_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_unique_everseen_tests" ],
    [ "UniqueJustseenTests", "classmore__itertools_1_1tests_1_1test__recipes_1_1_unique_justseen_tests.html", "classmore__itertools_1_1tests_1_1test__recipes_1_1_unique_justseen_tests" ]
];