var namespacepygame_1_1tests_1_1run__tests____tests_1_1print__stderr_1_1fake__2__test =
[
    [ "KeyModuleTest", "classpygame_1_1tests_1_1run__tests____tests_1_1print__stderr_1_1fake__2__test_1_1_key_module_test.html", "classpygame_1_1tests_1_1run__tests____tests_1_1print__stderr_1_1fake__2__test_1_1_key_module_test" ]
];